//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewPasswordForgotten {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewPasswordForgotten() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewPasswordForgotten", typeof(ResViewPasswordForgotten).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Hallo {0},&lt;/b&gt;&lt;br&gt;&lt;br&gt;du wolltest dein Passwort zurücksetzen. Benutze den Link um ein neues Passwort zu definieren.&lt;br&gt;&lt;strong&gt;Der Link ist nur für die nächsten zwei Stunden gültig.&lt;/strong&gt;&lt;br&gt;&lt;br&gt;&lt;a href=&quot;{1}/{2}&quot; &gt;Passwort zurücksetzen&lt;/a&gt;&lt;br&gt;&lt;br&gt;Solltest du nicht versucht haben das Passwort zurückzusetzen, kann dieses E-mail ignoriert werden.&lt;br&gt;&lt;br&gt;Mit freundlichen Grüßen,&lt;br&gt;Das Clever Dog Toy Team.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail gesendet.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        public static string PasswordForgotten {
            get {
                return ResourceManager.GetString("PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine E-Mail mit einer Anleitung, wie das Passwort zurückgesetz werden kann, wurde an deine E-Mail Adresse gesendet.
        /// </summary>
        public static string ResetEmailSent {
            get {
                return ResourceManager.GetString("ResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort zusenden.
        /// </summary>
        public static string SendNewPassword {
            get {
                return ResourceManager.GetString("SendNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server konnte nicht erreicht werden. Versuche es später nocheinmal.
        /// </summary>
        public static string ServerUnavailableText {
            get {
                return ResourceManager.GetString("ServerUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nicht erreichbar.
        /// </summary>
        public static string ServerUnavailableTitle {
            get {
                return ResourceManager.GetString("ServerUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
