//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewBluetooth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewBluetooth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewBluetooth", typeof(ResViewBluetooth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Futterspender verbinden?.
        /// </summary>
        public static string ConnectToFeeder {
            get {
                return ResourceManager.GetString("ConnectToFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Gerät verbinden?.
        /// </summary>
        public static string ConnectToNearbyDevice {
            get {
                return ResourceManager.GetString("ConnectToNearbyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerät verbunden.
        /// </summary>
        public static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerät gefunden.
        /// </summary>
        public static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stelle sicher das ein Gerät in der Nähe ist und Bluetooth aktiviert hat.
        /// </summary>
        public static string EnsureBluetoothDeviceNearby {
            get {
                return ResourceManager.GetString("EnsureBluetoothDeviceNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futterspender gefunden.
        /// </summary>
        public static string FeederFound {
            get {
                return ResourceManager.GetString("FeederFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In correctiontrial.
        /// </summary>
        public static string InCorrectionTrial {
            get {
                return ResourceManager.GetString("InCorrectionTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes trial war korrect.
        /// </summary>
        public static string LastTrialCorrect {
            get {
                return ResourceManager.GetString("LastTrialCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer des letzten Trials: .
        /// </summary>
        public static string LastTrialDuration {
            get {
                return ResourceManager.GetString("LastTrialDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes trial war inkorrect.
        /// </summary>
        public static string LastTrialIncorrect {
            get {
                return ResourceManager.GetString("LastTrialIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Gerät verbunden.
        /// </summary>
        public static string NoDeviceConnected {
            get {
                return ResourceManager.GetString("NoDeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Gerät gefunden.
        /// </summary>
        public static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Resultate.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Gerät verbunden. Nach Gerät suchen?.
        /// </summary>
        public static string SearchForDevice {
            get {
                return ResourceManager.GetString("SearchForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer der Session: .
        /// </summary>
        public static string SessionDuration {
            get {
                return ResourceManager.GetString("SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session beendet.
        /// </summary>
        public static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training jetzt starten?.
        /// </summary>
        public static string StartTrainingNow {
            get {
                return ResourceManager.GetString("StartTrainingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl an richtigen Antworten:.
        /// </summary>
        public static string TotalCorrect {
            get {
                return ResourceManager.GetString("TotalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl an Fehlern:.
        /// </summary>
        public static string TotalErrors {
            get {
                return ResourceManager.GetString("TotalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Nummer:.
        /// </summary>
        public static string TrialNumber {
            get {
                return ResourceManager.GetString("TrialNumber", resourceCulture);
            }
        }
    }
}
