//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewBluetoothSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewBluetoothSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewBluetoothSettings", typeof(ResViewBluetoothSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charakteristk ID.
        /// </summary>
        public static string CharacteristicId {
            get {
                return ResourceManager.GetString("CharacteristicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Futterspenders.
        /// </summary>
        public static string FeederName {
            get {
                return ResourceManager.GetString("FeederName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen der Futterspender.
        /// </summary>
        public static string FeederNames {
            get {
                return ResourceManager.GetString("FeederNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesecharakteristik IDs der Futterspender.
        /// </summary>
        public static string FeederReadCharacteristics {
            get {
                return ResourceManager.GetString("FeederReadCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID.
        /// </summary>
        public static string FeederServiceId {
            get {
                return ResourceManager.GetString("FeederServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service IDs der Futterspender.
        /// </summary>
        public static string FeederServices {
            get {
                return ResourceManager.GetString("FeederServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibcharakteristik IDs der Futterspender.
        /// </summary>
        public static string FeederWriteCharacteristics {
            get {
                return ResourceManager.GetString("FeederWriteCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene ID ist ungültig.
        /// </summary>
        public static string IdIsInvalid {
            get {
                return ResourceManager.GetString("IdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige ID.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID der Charakteristk, die hinzugefügt werden soll?.
        /// </summary>
        public static string WhatIsTheCharacteristicId {
            get {
                return ResourceManager.GetString("WhatIsTheCharacteristicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Futterspender, der hinzugefügt werden soll?.
        /// </summary>
        public static string WhatIsTheFeederName {
            get {
                return ResourceManager.GetString("WhatIsTheFeederName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID des Services, das hinzugefügt werden soll?.
        /// </summary>
        public static string WhatIsTheServiceId {
            get {
                return ResourceManager.GetString("WhatIsTheServiceId", resourceCulture);
            }
        }
    }
}
