//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAnimalRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAnimalRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewAnimalRegistration", typeof(ResViewAnimalRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie alt ist dein Hund?.
        /// </summary>
        public static string AgeOfAnimal {
            get {
                return ResourceManager.GetString("AgeOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasse.
        /// </summary>
        public static string Breed {
            get {
                return ResourceManager.GetString("Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welche Rasse hat dein Hund?.
        /// </summary>
        public static string BreedOfAnimal {
            get {
                return ResourceManager.GetString("BreedOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Tier kann nur mit einer aktiven Internetverbindung hinzugefügt werden.
        /// </summary>
        public static string CannotRegisterAnimalWithoutInternet {
            get {
                return ResourceManager.GetString("CannotRegisterAnimalWithoutInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilbild ändern.
        /// </summary>
        public static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden nicht alle benötigten Daten angegeben.
        /// </summary>
        public static string DataIncompleteText {
            get {
                return ResourceManager.GetString("DataIncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten unvollständig.
        /// </summary>
        public static string DataIncompleteTitle {
            get {
                return ResourceManager.GetString("DataIncompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist das Geburtsdatum deines Hundes? (Bitte so genau wie möglich).
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist das Geburtsdatum des Vogels?.
        /// </summary>
        public static string DateOfBirthBird {
            get {
                return ResourceManager.GetString("DateOfBirthBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiblich.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist dein Hund weiblich oder männlich?.
        /// </summary>
        public static string GenderOfAnimal {
            get {
                return ResourceManager.GetString("GenderOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist der Vogel weiblich oder männlich?.
        /// </summary>
        public static string GenderOfBird {
            get {
                return ResourceManager.GetString("GenderOfBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungultiger Rassenname!.
        /// </summary>
        public static string InvaldBreedName {
            get {
                return ResourceManager.GetString("InvaldBreedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logge dich online ein um einen neuen Hund hinzuzufügen
        ///
        ///Jetzt online einloggen?.
        /// </summary>
        public static string LogInToAddAnimal {
            get {
                return ResourceManager.GetString("LogInToAddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männlich.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monat.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie heißt dein Hund?.
        /// </summary>
        public static string NameOfAnimal {
            get {
                return ResourceManager.GetString("NameOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Vogels?.
        /// </summary>
        public static string NameOfBird {
            get {
                return ResourceManager.GetString("NameOfBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundeprofil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vogelprofil.
        /// </summary>
        public static string ProfileBird {
            get {
                return ResourceManager.GetString("ProfileBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Serverfehler ist aufgetreten. Bitte versuche es später nochmal.
        /// </summary>
        public static string ServerErrorText {
            get {
                return ResourceManager.GetString("ServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serverfehler.
        /// </summary>
        public static string ServerErrorTitle {
            get {
                return ResourceManager.GetString("ServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server konnte nicht erreicht werden. Bitte versuche es später nochmal.
        /// </summary>
        public static string ServerUnavailableText {
            get {
                return ResourceManager.GetString("ServerUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nicht erreichbar.
        /// </summary>
        public static string ServerUnavailableTitle {
            get {
                return ResourceManager.GetString("ServerUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahr.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
