//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewRegistration", typeof(ResViewRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Felder müssen ausgefüllt werden.
        /// </summary>
        public static string DataIncompleteText {
            get {
                return ResourceManager.GetString("DataIncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten unvollständig.
        /// </summary>
        public static string DataIncompleteTitle {
            get {
                return ResourceManager.GetString("DataIncompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde bereits ein Account mit der angegebenen E-Mail Addresse erstellt.
        /// </summary>
        public static string EmailInUseText {
            get {
                return ResourceManager.GetString("EmailInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse bereits in Verwendung.
        /// </summary>
        public static string EmailInUseTitle {
            get {
                return ResourceManager.GetString("EmailInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte eine gültige E-Mail Adresse angeben.
        /// </summary>
        public static string EmailInvalidText {
            get {
                return ResourceManager.GetString("EmailInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse nicht gültig.
        /// </summary>
        public static string EmailInvalidTitle {
            get {
                return ResourceManager.GetString("EmailInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die beiden angegeben Passwörter stimmen nicht überein.
        /// </summary>
        public static string PasswordErrorText {
            get {
                return ResourceManager.GetString("PasswordErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter fehlerhaft.
        /// </summary>
        public static string PasswordErrorTitle {
            get {
                return ResourceManager.GetString("PasswordErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mindestens 8 Zeichen lang sein.
        /// </summary>
        public static string PasswordTooShortText {
            get {
                return ResourceManager.GetString("PasswordTooShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zu kurz.
        /// </summary>
        public static string PasswordTooShortTitle {
            get {
                return ResourceManager.GetString("PasswordTooShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registriere.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Registrierung.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler am Server. Versuche es später nochmal.
        /// </summary>
        public static string ServerErrorText {
            get {
                return ResourceManager.GetString("ServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serverfehler.
        /// </summary>
        public static string ServerErrorTitle {
            get {
                return ResourceManager.GetString("ServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server konnte nicht erreicht werden.
        /// </summary>
        public static string ServerUnavailableText {
            get {
                return ResourceManager.GetString("ServerUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nicht erreichbar.
        /// </summary>
        public static string ServerUnavailableTitle {
            get {
                return ResourceManager.GetString("ServerUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenschutzerklärung sowie die Allgemeinen Geschäftsbedinungungen müssen gelesen und akzeptiert werden.
        /// </summary>
        public static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung und Allgemeine Geschäftsbedinungungen.
        /// </summary>
        public static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe die .
        /// </summary>
        public static string TermsStatement1 {
            get {
                return ResourceManager.GetString("TermsStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        public static string TermsStatement2 {
            get {
                return ResourceManager.GetString("TermsStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sowie die .
        /// </summary>
        public static string TermsStatement3 {
            get {
                return ResourceManager.GetString("TermsStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeinen Geschäftsbedingungen.
        /// </summary>
        public static string TermsStatement4 {
            get {
                return ResourceManager.GetString("TermsStatement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  gelesen und akzeptiert.
        /// </summary>
        public static string TermsStatement5 {
            get {
                return ResourceManager.GetString("TermsStatement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Benutzername wird bereits von einem anderen Benutzer verwendet.
        /// </summary>
        public static string UsernameInUseText {
            get {
                return ResourceManager.GetString("UsernameInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername in Verwendung.
        /// </summary>
        public static string UsernameInUseTitle {
            get {
                return ResourceManager.GetString("UsernameInUseTitle", resourceCulture);
            }
        }
    }
}
