//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewStatistics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewStatistics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewStatistics", typeof(ResViewStatistics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie oft gespielt: .
        /// </summary>
        public static string AmountPlayed {
            get {
                return ResourceManager.GetString("AmountPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestes Ergebnis (wenigste Fehler): .
        /// </summary>
        public static string BestResult {
            get {
                return ResourceManager.GetString("BestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Details konnten nicht vom Server geladen werden
        ///Versuche es später nochmal.
        /// </summary>
        public static string CouldNotLoadStatistics {
            get {
                return ResourceManager.GetString("CouldNotLoadStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer des Trainings: .
        /// </summary>
        public static string DurationOfTraining {
            get {
                return ResourceManager.GetString("DurationOfTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details werden geladen.
        /// </summary>
        public static string LoadingDetails {
            get {
                return ResourceManager.GetString("LoadingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logge dich online ein um die Statistikdetails anzusehen
        ///
        ///Jetzt online einloggen?.
        /// </summary>
        public static string LogInOnlineToViewStatDetails {
            get {
                return ResourceManager.GetString("LogInOnlineToViewStatDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viele Fehler: .
        /// </summary>
        public static string NumberOfErrors {
            get {
                return ResourceManager.GetString("NumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunden.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server nicht erreichbar.
        /// </summary>
        public static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details zu den Statistiken können nicht ohne Internetverbindung abgerufen werden.
        /// </summary>
        public static string ShowStatisticDetailsNoInternet {
            get {
                return ResourceManager.GetString("ShowStatisticDetailsNoInternet", resourceCulture);
            }
        }
    }
}
