//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriBase.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewTrainingType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewTrainingType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriBase.Models.Resources.ResViewTrainingType", typeof(ResViewTrainingType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string DeathRecognition {
            get {
                return ResourceManager.GetString("DeathRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string DeathRecognitionTraining1 {
            get {
                return ResourceManager.GetString("DeathRecognitionTraining1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string DeathRecognitionTraining2 {
            get {
                return ResourceManager.GetString("DeathRecognitionTraining2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganzer Touchscreen.
        /// </summary>
        public static string EntireTouchscreenTraining {
            get {
                return ResourceManager.GetString("EntireTouchscreenTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoNoGo.
        /// </summary>
        public static string GoNoGo {
            get {
                return ResourceManager.GetString("GoNoGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beispielbild.
        /// </summary>
        public static string MatchingToSample {
            get {
                return ResourceManager.GetString("MatchingToSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zufällige Positionen.
        /// </summary>
        public static string RndPosTest {
            get {
                return ResourceManager.GetString("RndPosTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequenz lernen.
        /// </summary>
        public static string SequentialLearning {
            get {
                return ResourceManager.GetString("SequentialLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrere Bilder.
        /// </summary>
        public static string SeveralImgTest {
            get {
                return ResourceManager.GetString("SeveralImgTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Bild auf zufälliger Position.
        /// </summary>
        public static string SingleImageMultiplePositionsTraining {
            get {
                return ResourceManager.GetString("SingleImageMultiplePositionsTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Bild.
        /// </summary>
        public static string SingleImageTraining {
            get {
                return ResourceManager.GetString("SingleImageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei Bilder.
        /// </summary>
        public static string TwoImgTest {
            get {
                return ResourceManager.GetString("TwoImgTest", resourceCulture);
            }
        }
    }
}
