on:
  push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'

name: Create MriDogApp Android Apk Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution
        run: msbuild ./MriBase.sln /restore /p:Configuration=Release

      - name: Create and Sign the APK
        run: msbuild MriBase.App.Dog\MriBase.App.Dog.Android\MriBase.App.Dog.Android.csproj /t:SignAndroidPackage /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MriDogApp.apk
          path: MriBase.App.Dog\MriBase.App.Dog.Android\bin\Release\mribase.app.dog-Signed.apk
          
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.push.ref }}
        run: |
          tag=${ref##*/}

          gh release upload "$tag" MriDogApp.apk --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${tag#v}" --generate-notes
